name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/zetraison/gitlab-telegram-bot/gitlab-telegram-bot:latest
      
    - name: Push the Docker image to Github Registry
      run: docker push docker.pkg.github.com/zetraison/gitlab-telegram-bot/gitlab-telegram-bot:latest

    - name: Push the Docker image to DockerHub Registry
      run: docker push zetraison/gitlab-telegram-bot:latest
